spring.datasource.url=jdbc:mysql://localhost:3306/health_monitor
spring.datasource.username=root
spring.datasource.password=Kavi@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081